### PR TITLE
Configurable cache size for processing validations

### PR DESCRIPTION
**Pull request by mmolimar**
It'd be nice to set the cache size in source code when processing validations

### CODE REVIEW

**Comment by huggsboson** [comment]
Looks good.  If you address my comments in the other patchset I can merge that, do a build/release to com.box:json-schema-core and then merge this.

**Comment by mmolimar** [comment]
I changed the default cache size to 512 :-)

**Comment by huggsboson** [comment]
Merging release should be available in 30 minutes.  Thanks for the contribution.

**Comment by huggsboson** [comment]
The validator should be available at com.box:json-schema-validator 2.2.10.

Let me know if you have any issues.

**Comment by mmolimar** [comment]
Perfect, I just saw it! Thanks ;-)

**Pull request merged**
